spring:
  application:
    name: HelloClient

feign:  client:    config:      default:
        connect-timeout: 2000
        read-timeout: 2000
        logger-level: basic  hystrix:    enabled: true

server:
  port: 7211

eureka:
  password: password
  client:
    serviceUrl:
      defaultZone: http://user:${eureka.password}@localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}


endpoints:
  restart:
    enabled: true